### ISSUE TITLE
Update and standardize documentation and meta-files (Readme, Contributing, Authors, Release Guide, etc)

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/docrepr#37]
* [x] Update AUTHORS, LICENSE.txt and __init__ w/standard format and link to authors
* [x] Update links to HTTPS and check old
* [x] Update Readme text and formatting and make OLPS
* [x] Add contributing guide
* [x] Add security policy
* [x] Update release guide

Also incorporates #20
